version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finpay
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
